fixed #7

diff --git a/roles/redmine/templates/init_redmine.j2 b/roles/redmine/templates/init_redmine.j2
--- a/roles/redmine/templates/init_redmine.j2
+++ b/roles/redmine/templates/init_redmine.j2
@@ -19,71 +19,106 @@
 RAILS_ENV="production"
 
 # Feel free to change any of the following variables for your app:
-TIMEOUT=${TIMEOUT-60}
 APP_ROOT={{ redmine_home }}/redmine
 APP_USER="redmine"
-PID=$APP_ROOT/tmp/pids/unicorn.pid
-CMD="/home/redmine/.rbenv/shims/bundle exec unicorn_rails -D -c $APP_ROOT/config/unicorn.rb -E $RAILS_ENV"
-INIT_CONF=$APP_ROOT/config/init.conf
+PID=${APP_ROOT}/tmp/pids/unicorn.pid
+CMD="/home/redmine/.rbenv/shims/bundle exec unicorn_rails -D -c ${APP_ROOT}/config/unicorn.rb -E ${RAILS_ENV}"
+INIT_CONF=${APP_ROOT}/config/init.conf
 action="$1"
+RETVAL=0
+prog="redmine"
 
-test -f "$INIT_CONF" && . $INIT_CONF
+test -f "${INIT_CONF}" && . ${INIT_CONF}
 
-old_pid="$PID.oldbin"
+cd ${APP_ROOT} || exit 1
 
-cd $APP_ROOT || exit 1
-
-sig () {
-	test -s "$PID" && kill -$1 `cat $PID`
+start(){
+  echo -n $"Starting $prog: "
+  daemon --pidfile=${PID} --user=${APP_USER} "cd ${APP_ROOT} && ${CMD}" 
+  RETVAL=$?
+  echo
 }
 
-oldsig () {
-	test -s $old_pid && kill -$1 `cat $old_pid`
+stop(){
+  echo -n $"Stopping $prog: "
+  killproc -p ${PID} ${prog} -QUIT
+  RETVAL=$?
+  echo
+}
+
+rh_status() {
+    status -p ${PID} ${prog}
+}
+
+force_stop(){
+  echo -n $"Force-Stopping $prog: "
+  killproc -p ${PID} ${prog} -TERM
+  RETVAL=$?
+  echo
+}
+
+reload(){
+  echo -n $"Reloading $prog: "
+  killproc -p ${PID} ${prog} -HUP
+  RETVAL=$?
+  echo
+}
+
+upgrade(){
+  old_pid=${PID}.oldbin
+  echo -n $"Staring new master $prog: "
+  killproc -p ${PID} ${prog} -USR2
+  RETVAL=$?
+  echo
+  sleep 2
+  if [ -f ${old_pid} -a -f ${PID} ]; then
+      echo -n $"Graceful shutdown of old $prog: "
+      killproc -p ${old_pid} ${prog} -QUIT
+      RETVAL=$?
+      echo 
+  else
+      echo $"Upgrade failed!"
+      return 1
+  fi
+}
+
+reopen_logs(){
+  echo -n $"ReOpening Logs $prog: "
+  killproc -p ${PID} ${prog} -USR1
+  RETVAL=$?
+  echo
 }
 
 case $action in
 start)
-	sig 0 && echo >&2 "Already running" && exit 0
-	sudo -u $APP_USER sh -c "cd $APP_ROOT && $CMD"
-	;;
+  start
+  ;;
 stop)
-	sig QUIT && exit 0
-	echo >&2 "Not running"
-	;;
-force-stop)
-	sig TERM && exit 0
-	echo >&2 "Not running"
-	;;
-restart|reload)
-	sig HUP && echo reloaded OK && exit 0
-	echo >&2 "Couldn't reload, starting '$CMD' instead"
-	sudo -u $APP_USER sh -c "cd $APP_ROOT && $CMD"
-	;;
+  stop
+  ;;
+status)
+  rh_status
+  ;;
+restart)
+  stop
+  sleep 2
+  start
+  ;;
+reload)
+  reload
+  ;;
 upgrade)
-	if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
-	then
-		n=$TIMEOUT
-		while test -s $old_pid && test $n -ge 0
-		do
-			printf '.' && sleep 1 && n=$(( $n - 1 ))
-		done
-		echo
-
-		if test $n -lt 0 && test -s $old_pid
-		then
-			echo >&2 "$old_pid still exists after $TIMEOUT seconds"
-			exit 1
-		fi
-		exit 0
-	fi
-	echo >&2 "Couldn't upgrade, starting '$CMD' instead"
-	sudo -u $APP_USER sh -c "cd $APP_ROOT && $CMD"
-	;;
+  upgrade
+  ;;
+force-stop)
+  force_stop
+  ;;
 reopen-logs)
-	sig USR1
-	;;
+  reopen_logs
+  ;;
 *)
-	echo >&2 "Usage: $0 <start|stop|restart|upgrade|force-stop|reopen-logs>"
-	exit 1
-	;;
+  echo >&2 "Usage: $0 <start|stop|restart|reload|upgrade|force-stop|reopen-logs>"
+  exit 1
+  ;;
 esac
+exit 0
